### initialize
POST http://localhost:3000/mcp
Content-Type: application/json
Accept: application/json, text/event-stream

{
  "jsonrpc": "2.0",
  "id": "init-1",
  "method": "initialize",
  "params": {
    "protocolVersion": "2024-11-05",
    "capabilities": {
      "tools": {}
    },
    "clientInfo": {
      "name": "test-client",
      "version": "1.0.0"
    }
  }
}

### notifications/initialized, get mcp-session-id from "initialize" response header
POST http://localhost:3000/mcp
Content-Type: application/json
Accept: application/json, text/event-stream
mcp-session-id: 59ef6d83-99a6-40e5-93fc-a576495691d6

{
  "jsonrpc": "2.0",
  "method": "notifications/initialized"
}